
package eu.wisebed.api.snaa;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eu.wisebed.api.common.SecretAuthenticationKey;
import eu.wisebed.api.common.UsernameUrnPrefixPair;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SNAA", targetNamespace = "http://testbed.wisebed.eu/api/snaa/v1/")
@XmlSeeAlso({
    eu.wisebed.api.snaa.ObjectFactory.class,
    eu.wisebed.api.common.ObjectFactory.class
})
public interface SNAA {


    /**
     * 
     * @param authenticationData
     * @return
     *     returns java.util.List<eu.wisebed.api.common.SecretAuthenticationKey>
     * @throws AuthenticationExceptionException
     * @throws SNAAExceptionException
     */
    @WebMethod
    @WebResult(name = "secretAuthenticationKey", targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://testbed.wisebed.eu/api/snaa/v1/", className = "eu.wisebed.api.snaa.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://testbed.wisebed.eu/api/snaa/v1/", className = "eu.wisebed.api.snaa.AuthenticateResponse")
    public List<SecretAuthenticationKey> authenticate(
        @WebParam(name = "authenticationData", targetNamespace = "")
        List<AuthenticationTriple> authenticationData)
        throws AuthenticationExceptionException, SNAAExceptionException
    ;

    /**
     * 
     * @param usernames
     * @param action
     * @param nodeUrns
     * @return
     *     returns eu.wisebed.api.snaa.AuthorizationResponse
     * @throws SNAAExceptionException
     */
    @WebMethod
    @WebResult(name = "resp", targetNamespace = "")
    @RequestWrapper(localName = "isAuthorized", targetNamespace = "http://testbed.wisebed.eu/api/snaa/v1/", className = "eu.wisebed.api.snaa.IsAuthorized")
    @ResponseWrapper(localName = "isAuthorizedResponse", targetNamespace = "http://testbed.wisebed.eu/api/snaa/v1/", className = "eu.wisebed.api.snaa.IsAuthorizedResponse")
    public AuthorizationResponse isAuthorized(
        @WebParam(name = "usernames", targetNamespace = "")
        List<UsernameUrnPrefixPair> usernames,
        @WebParam(name = "action", targetNamespace = "")
        Action action,
        @WebParam(name = "nodeUrns", targetNamespace = "")
        String nodeUrns)
        throws SNAAExceptionException
    ;

}
